title: Vyom Vertigo
tagline: "A celebration of movies and stories. Unless those stories are about self-help books—then I hate them with a passion."
description: A minimalist space (mostly due to laziness) dedicated to sharing my love for film, screenwriting, and storytelling. I legally have to use the word 'cinematic' here or my pretentious cinephile license gets revoked.
url: ""
author: Vyom Pandya

# Social Links & Contact
instagram_url: "https://www.instagram.com/vyom_vertigo?igsh=aHBlZGl4ZjQzeXF6&utm_source=qr"
letterboxd_url: "https://boxd.it/3LL6R"
email: "vyomvertigo@gmail.com"

# Build Settings
permalink: /posts/:title/
markdown: kramdown
highlighter: rouge
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .github
  - README.md
